version: "3.8"

services:
  web:
    container_name: web
    build: .
    env_file:
      - .env
    ports:
      - 3000:3000
    develop:
      watch:
        - action: sync
          path: .
          target: /app
        - action: rebuild
          path: go.mod

  db:
    platform: linux/x86_64
    container_name: db
    image: mysql:8
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:5.2.1
    env_file:
      - .env
    ports:
      - 80:80

volumes:
  db:
